apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argo-cd-role
rules:
- apiGroups: [""]
  resources: ["applications"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argocd
  name: argo-cd-role-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
roleRef:
  kind: Role
  name: argo-cd-role
  apiGroup: rbac.authorization.k8s.io