apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: backend
  name: backend
spec:
  ports:
    - name: "88"
      port: 88
      targetPort: 8080
  selector:
    service: backend
status:
  loadBalancer: {}
